---
title: "About NFIDD"
---

## What is NFIDD?

NFIDD (Nowcasting and Forecasting Infectious Disease Dynamics) is an MIT-licensed library of sessions for learning about nowcasting and forecasting of infectious disease surveillance data.
This course is a living resource designed to help epidemiologists, public health professionals, and researchers understand and apply real-time analysis methods to infectious disease surveillance data.

## Course Authors

The NFIDD course was developed by the **NFIDD course contributors**:

- [Sam Abbott](https://github.com/seabbs)
- [Katherine Sherratt](https://github.com/kathsherratt)
- [Sebastian Funk](https://github.com/sbfnk)

## How to Cite

If you use materials from this course in your work, please cite:

> NFIDD course contributors (2025). NFIDD: Nowcasting and Forecasting Infectious Disease Dynamics. Version [VERSION]. DOI: [PLACEHOLDER - Zenodo DOI will be added upon release]

### BibTeX Entry

```bibtex
@misc{nfidd2025,
  author = {{Sam Abbott, Katherine Sherratt, Sebastian Funk}},
  title = {{NFIDD: Nowcasting and Forecasting Infectious Disease Dynamics}},
  year = {2025},
  version = {[VERSION]},
  doi = {[PLACEHOLDER - Zenodo DOI]},
  url = {https://nfidd.github.io/nfidd/}
}
```

## License

All course materials are provided under the [MIT License](https://opensource.org/licenses/MIT), making them freely available for teaching, learning, and adaptation.

## Contributing

We welcome contributions to improve and expand the course materials.
You can:

- [Report issues or suggest improvements](https://github.com/nfidd/nfidd/issues)
- [Join discussions](https://github.com/nfidd/nfidd/discussions)
- [Submit pull requests](https://github.com/nfidd/nfidd/pulls)

## Acknowledgements

We thank all participants who have helped improve these materials through feedback, bug reports, and code contributions.