---
title: "Authors"
---

The NFIDD course was developed by the **NFIDD course contributors**:

- [Sam Abbott](https://github.com/seabbs)
- [Kath Sherratt](https://github.com/kathsherratt)
- [Sebastian Funk](https://github.com/sbfnk)

The SISMID course was adapted by the **SISMID course contributors**:

- [Sam Abbott](https://github.com/seabbs)
- [Thomas Robacker](https://github.com/trobacker)
- [Nick Reich](https://github.com/nickreich)

## How to Cite

If you use materials from this course in your work, please cite:

> NFIDD course contributors (2025). NFIDD: Nowcasting and Forecasting Infectious Disease Dynamics. Version [VERSION]. DOI: [PLACEHOLDER - Zenodo DOI will be added upon release]

> SISMID course contributors (2025). NFIDD SISMID: Nowcasting and Forecasting Infectious Disease Dynamics - SISMID. Version [VERSION]. DOI: [PLACEHOLDER - Zenodo DOI will be added upon release]

### BibTeX Entry

```bibtex
@misc{nfidd2025,
  author = {{Sam Abbott, Katherine Sherratt, Sebastian Funk}},
  title = {{NFIDD: Nowcasting and Forecasting Infectious Disease Dynamics}},
  year = {2025},
  version = {[VERSION]},
  doi = {[PLACEHOLDER - Zenodo DOI]},
  url = {https://nfidd.github.io/nfidd/}
}
```

```bibtex
@misc{sismid2025,
  author = {{Sam Abbott, Thomas Robacker, Nick Reich}},
  title = {{NFIDD SISMID: Nowcasting and Forecasting Infectious Disease Dynamics - SISMID}},
  year = {2025},
  version = {[VERSION]},
  doi = {[PLACEHOLDER - Zenodo DOI]},
  url = {https://nfidd.github.io/sismid/}
}
```

## Funding

These training materials have been developed with support by the National Institutes of General Medical Sciences (R35GM119582), the US Centers for Disease Control and Prevention (NU38FT000008), and the Wellcome Trust (210758/Z/18/Z). The content is solely the responsibility of the authors and does not necessarily represent the official views of NIGMS, the National Institutes of Health, the CDC, or the Wellcome Trust.

## License

All course materials are provided under the [MIT License](https://opensource.org/licenses/MIT), making them freely available for teaching, learning, and adaptation.

## Contributing

We welcome contributions to improve and expand the course materials.
You can:

- [Report issues or suggest improvements](https://github.com/nfidd/nfidd/issues)
- [Join discussions](https://github.com/nfidd/nfidd/discussions)
- [Submit pull requests](https://github.com/nfidd/nfidd/pulls)

## Acknowledgements

We thank all participants who have helped improve these materials through feedback, bug reports, and code contributions.
