---
title: "Sessions"
comments: false
---

# Day 1: Deconstructing epidemiological timelines

**Monday June 23**

## Session 0: Introduction and course overview

Monday June 23: 09.00-09.30

-   [Introduction](introduction-to-the-course-and-the-instructors.qmd): the course and the instructors (10 mins)
-   [Motivating the course](from-line-list-to-decisions.qmd): From an epidemiological line list to informing decisions in real-time (20 mins)

## Session 1: R, Stan, and statistical concept background

Monday June 23: 09.30-10.30

-   [Introduction](sessions/slides/introduction-to-statistical-concepts): statistical concepts used in the course (15 mins)
-   [Introduction](sessions/slides/introduction-to-stan): stan concepts used in the course (15 mins)
-   [Practice](sessions/R-Stan-and-statistical-concepts): introduction to estimation in stan (30 mins)

## Session 2: Delay distributions

Monday June 23: 11.00-11.45

-   [Introduction](sessions/slides/introduction-to-epidemiological-delays.qmd): epidemiological delays and how to represent them with probability distributions (10 mins)
-   [Practice](delay-distributions.qmd): simulate and estimate epidemiological delays (30 mins)
-   Wrap up (5 mins)

## Session 3: Biases in delay distributions

Monday June 23: 11.45-12.30 and 14.00-14.45

-   [Introduction](sessions/slides/introduction-to-biases-in-epidemiological-delays.qmd): biases in delay distributions (10 mins)
-   [Practice](sessions/biases-in-delay-distributions.qmd): 
    - simulating biases in delay distributions and estimating delays without adjustment on these data (35 mins)
    - estimating delay distributions with adjustments for bias (35 mins)
-   Wrap up (10 mins)

## Session 4: Using delay distributions to model the data generating process of an epidemic

Monday June 23: 14.45-15.30

-   [Introduction](convolutions.qmd): Using delay distributions to model the data generating process of an epidemic (15 mins)
-   [Practice](sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd): implementing a convolution model and identifying potential problems (30 mins)

## Session 5: $R_t$ estimation and the renewal equation

Monday June 23: 16.00-17.30

-   [Introduction](sessions/slides/introduction-to-reproduction-number.qmd): the time-varying reproduction number (10 mins)
-   [Practice](sessions/R-estimation-and-the-renewal-equation.qmd): 
    - using the renewal equation to estimate R (35 mins)
    - combining $R_t$ estimation with delay distribution convolutions (35 mins)
-   Wrap up (10 mins)

# Day 2: Constructing nowcasts and forecasts

**Tuesday June 24**

Tuesday June 24: 09.00-09.15

-   Day 1 review

## Session 6: Nowcasting concepts

Tuesday June 24: 09.15-10.30

-   [Introduction](sessions/slides/introduction-to-nowcasting.qmd): nowcasting as a right-truncation problem (10 mins)
-   [Practice](sessions/nowcasting.qmd): 
    - simulating the delay distribution (35 mins)
    - nowcasting using pre-estimated delay distributions (35 mins)
-   Wrap up (10 mins)

## Session 7: Nowcasting with an unknown reporting delay

Tuesday June 24: 11.00-12.30

-   [Introduction](sessions/slides/introduction-to-joint-estimation-of-nowcasting-and-reporting-delays.qmd): joint estimation of delays and nowcasts (10 mins)
-   [Practice](sessions/joint-nowcasting.qmd):
    - joint estimation of delays and nowcasts (35 mins)
    - joint estimation of delays, nowcasts and reproduction numbers (35 mins)
-   Wrap up (10 mins)

## Session 8: Forecasting concepts

Tuesday June 24: 14.00-15.30

-   [Introduction](sessions/slides/forecasting-as-an-epidemiological-problem.qmd): forecasting as an epidemiological problem, and its relationship with nowcasting and $R_t$ estimation (10 mins)
-   [Practice](sessions/forecast-visualisation.qmd): extending a model into the future, visualising and evaluating your forecast (30 minutes)
-   [Introduction](sessions/slides/forecast-evaluation.qmd): quantitatively evaluating forecasts (10 mins)
-   [Practice](sessions/forecast-evaluation.qmd): evaluating forecasts with a range of metrics (30 mins)
-   Wrap up (10 mins)

## Session 9: Forecasting models

Tuesday June 24: 16.00-17.30

-   [Introduction](sessions/slides/introduction-to-the-spectrum-of-forecasting-models.qmd): a spectrum of forecasting models (10 mins)
-   [Practice](sessions/forecasting-models.qmd): evaluating forecasts from a range of models (60 mins)
-   Wrap up & discussion (20 mins)

# Day 3: Reconstructing - ensembles and applications

**Wednesday June 25**

Wednesday June 25: 09.00-09.15

-   Day 2 review

## Session 10: Forecasting with ensembles

Wednesday June 25: 09.15-10.30

-   [Introduction](sessions/slides/introduction-to-ensembles.qmd): strategies for collating and combining models
-   [Practice](sessions/forecast-ensembles): evaluating methods for ensemble forecasts

## Session 11: Methods in the real world

Wednesday June 25: 11.00-12.00

-   Presentations and Q&A on uses of nowcasts & forecasts in the real world (60 mins)

## Session 12: End of course summary

Wednesday June 25: 12.00-12.30

-   [Summary](sessions/slides/closing.qmd) of the course (10 mins)
-   Final discussion and closing (20 mins)
    - [Further reading](end-of-course-summary-and-discussion.qmd)
