---
title: "Further reading"
order: 13
---

# Further reading

The following is a highly subjective list of papers we would recommend to read for those interested in engaging further with the topics discussed here. You can also access this via Zotero in an open [living library](https://www.zotero.org/groups/6031904/nowcasting_and_forecasting_infectious_disease_dynamics/library), which you are welcome to contribute to.

## Delay estimation
- @parkEstimatingEpidemiologicalDelay2024 provides a comprehensive overview of challenges in estimating delay distribution and how to overcome them.
- @charnigaBestPracticesEstimating2024 summarises challenges in estimating delay distributions into a set of best practices.

## $R_t$ estimation
- @gosticPracticalConsiderationsMeasuring2020 provides an overview of some of the challenges in estimating reproduction numbers.
- @brockhausWhyAreDifferent2023 compares reproduction number estimates from different models and investigates their differences.

## Nowcasting
- @wolfframCollaborativeNowcastingCOVID192023 compares the performance of a range of methods that were used in a nowcasting hub and investigates what might explain performance differences.
- @lisonGenerativeBayesianModeling2024 develops a generative model for nowcasting and $R_t$ estimation and compares its performance to an approach where the steps for estimating incidence and reproduction number are separated.
- @stonerPowerfulModellingFramework2020 contains a nice review of different methods for nowcasting evaluates a range of methods, in addition to introducing a new approach.

## Forecasting
- @funkAssessingPerformanceRealtime2019 evaluates the performance of a forecasting method that combines a mechanistic SEIR model with a random walk prior for the reproduction number.
- @heldProbabilisticForecastingInfectious2017 makes a compelling argument for the use of probabilistic forecasts and evaluates spatial forecasts based on routine surveillance data.
- @lopezChallengesCOVID19Case2024 describes the difficulty encountered in  making accurate forecasts in COVID-19 cases in the US COVID-19 Forecast Hub.
- @asherForecastingEbolaRegression2018 describes model that implements an extension to the random walk with a drift term.
- @CDCgovWastewaterinformedcovidforecasting2025, code repo for [Wastewater-informed COVID-19 forecasting](https://github.com/CDCgov/wastewater-informed-covid-forecasting).
- @hyndmanForecastingPrinciplesPractice2021 is a free online text book on forecasting with a range of time series models and a great resource for finding out more about them.

## Ensembles
- @sherrattPredictivePerformanceMultimodel2023 investigates the performance of different ensembles in the European COVID-19 Forecast Hub.
- @amaralPostprocessingWeightedCombination2025 discusses the challenges in improving on the predictive performance of simpler approaches using weighted ensembles.

## References

::: {#refs}
:::
