---
title: "Session timetable"
order: 1
comments: false
---

# Day 1: Epidemiological delays

**Wednesday - Half day starting at 1pm**

## Session 0: Introduction and course overview

Wednesday: 13.00-13.30

-   [Introduction](../sessions/slides/introduction-to-the-course-and-the-instructors): the course and the instructors (10 mins)
-   [Motivating the course](../sessions/slides/from-line-list-to-decisions): From an epidemiological line list to informing decisions in real-time (10 mins)
-   [Getting setup and using the course](../sessions/slides/getting-setup-and-using-the-course): setup, course navigation, and Stan intro (10 mins)

## Session 1: Delay distributions

Wednesday: 13.30-14.15

-   [Introduction](../sessions/slides/introduction-to-epidemiological-delays): epidemiological delays and how to represent them with probability distributions (10 mins)
-   [Practice](../sessions/delay-distributions): simulate and estimate epidemiological delays (30 mins)
-   Wrap up (5 mins)

## Session 2: Biases in delay distributions

Wednesday: 14.15-15.00

-   [Introduction](../sessions/slides/introduction-to-biases-in-epidemiological-delays): biases in delay distributions (10 mins)
-   [Practice](../sessions/biases-in-delay-distributions): simulating biases in delay distributions and estimating delays without adjustment on these data (30 mins)
-   Wrap up (5 mins)

## Session 3: Adjusting for biases in delay distributions

Wednesday: 15.30-16.15

-   [Introduction](../sessions/slides/adjusting-for-biases-in-delay-distributions): fitting models that adjust for biases (10 mins)
-   [Practice](../sessions/biases-in-delay-distributions): estimating delay distributions with adjustments for bias (30 mins)
-   Wrap up (5 mins)

## Session 4: Using delay distributions to model the data generating process of an epidemic

Wednesday: 16.15-17.00

-   [Introduction](../sessions/slides/convolutions): Using delay distributions to model the data generating process of an epidemic (10 mins)
-   [Practice](../sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic): implementing a convolution model and identifying potential problems (30 mins)
-   Wrap up (5 mins)

# Day 2: An introduction to nowcasting and forecasting

**Thursday - Full day**

Thursday: 09.00-09.15

-   Day 1 review (15 mins)

## Session 5: $R_t$ estimation and the renewal equation

Thursday: 09.15-10.00

-   [Introduction](../sessions/slides/introduction-to-reproduction-number): the time-varying reproduction number (10 mins)
-   [Practice](../sessions/R-estimation-and-the-renewal-equation): using the renewal equation to estimate R (30 mins)
-   Wrap up (5 mins)

## Session 6: Nowcasting concepts

Thursday: 10.00-10.30

-   [Introduction](../sessions/slides/introduction-to-nowcasting): nowcasting as a right-truncation problem (10 mins)
-   [Practice](../sessions/nowcasting): simulating and basic nowcasting (20 mins)

## Session 7: Nowcasting with an unknown reporting delay

Thursday: 11.00-12.00

-   [Introduction](../sessions/slides/introduction-to-joint-estimation-of-nowcasting-and-reporting-delays): joint estimation of delays and nowcasts (10 mins)
-   [Practice](../sessions/joint-nowcasting):
    - joint estimation of delays and nowcasts (20 mins)
    - joint estimation of delays, nowcasts and reproduction numbers (20 mins)
-   Wrap up (10 mins)

Thursday: 12.00-13.00

-   Lunch

## Session 8: Forecasting concepts

Thursday: 13.00-13.30

-   [Introduction](../sessions/slides/introduction-to-forecasting): forecasting as an epidemiological problem (10 mins)
-   [Practice](../sessions/forecasting-concepts): basic forecasting with ARIMA models (20 mins)

## Session 9: Improving forecasting models

Thursday: 13.30-14.15

-   [Introduction](../sessions/slides/improving-forecasting-models): ARIMA concepts and transformations (10 mins)
-   [Practice](../sessions/improving-forecasting-models): ACF plots, transformations, and seasonality (30 mins)
-   Wrap up (5 mins)

## Session 10: Forecast evaluation

Thursday: 14.15-15.00

-   [Introduction](../sessions/slides/forecast-evaluation): scoring rules and metrics (10 mins)
-   [Practice](../sessions/forecast-evaluation): evaluating forecasts with various metrics (30 mins)
-   Wrap up (5 mins)

## Session 11: Forecasting with ensembles

Thursday: 15.30-17.00

-   [Introduction](../sessions/slides/introduction-to-ensembles): strategies for collating and combining models (10 mins)
-   [Practice](../sessions/forecast-ensembles): evaluating methods for ensemble forecasts (75 mins)
-   Wrap up (5 mins)

# Day 3: Forecast hubs, advanced topics and course summary

**Friday - Full day**

Friday: 09.00-09.15

-   Day 2 review (15 mins)

## Session 12: Forecast hubs

Friday: 09.15-10.30

-   [Introduction](../sessions/slides/forecast-hubs): hub concepts and data structures (10 mins)
-   [Practice](../sessions/forecast-hubs): 
    - evaluation example with existing hub (30 mins)
    - ensembles with existing hub (30 mins)
-   Wrap up (5 mins)

## Session 13: Local hub playground

Friday: 11.00-12.00

-   [Introduction](../sessions/slides/hub-playground): Why a local hub? (10 mins)
-   [Practice](../sessions/hub-playground): getting stuck in with a local hub (45 mins)
-   Wrap up (5 mins)

Friday: 12.00-13.00

-   Lunch

## Session 14: Combining nowcasting and forecasting

Friday: 13.00-14.00

-   [Introduction](../sessions/slides/forecasting-nowcasting): Why combine approaches? (10 mins)
-   [Practice](../sessions/forecasting-nowcasting): connecting nowcasting and forecasting (45 mins)
-   Wrap up (5 mins)

## Session 15: Advanced topics

Friday: 14.00-15.00

-   [Introduction](../sessions/slides/advanced-forecasting): hierarchical ARIMA or forecast reconciliation (10 mins)
-   [Practice](../sessions/advanced-forecasting): hierarchical ARIMA or forecast reconciliation (45 mins)
-   Wrap up (5 mins)

## Session 16: Research talks and wrap-up

Friday: 15.30-17.00

-   Research talk 1: Nick (15 mins)
-   Research talk 2: Sam (15 mins)
-   Research talk 3: Nick (15 mins)
-   Research talk 4: Sam (15 mins)
-   [Summary](../sessions/slides/closing) of the course (10 mins)
-   Final discussion and closing (20 mins)
    - [Further reading](../sessions/end-of-course-summary-and-discussion)
