# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "infection_time", # <add_delays>
  "onset_time", # <add_delays>
  "hosp_time", # <add_delays>
  "infection_time", # <make_daily_infections>
  "infection_day", # <make_daily_infections>
  "infection_day", # <simulate_onsets>
  "infections", # <simulate_onsets>
  NULL
))
